[general]
framerate = 30
bars = 64
sensitivity = 120

[input]
method = pulse
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59
frame_delimiter = 10

[smoothing]
noise_reduction = 66

[eq]
1 = 1.2
2 = 1
3 = 1
4 = 1
5 = 0.8
